### ISSUE TITLE
filename not visible

### ISSUE THREAD

**Issue by Hboni** [Hboni/francis#10]
In the "load image" node, the image field is so small that it is not really possible to see the image name loaded, I can only see the extension before apply, which is not really convenient.  It is also not possible to use cursor and move with arrow keys in the filename to go to see more about the filename.
To improve visibility, it is possible to move browse button under between filename and the apply button ? Or use of an icon instead of text for browse button ? Or maybe increase node default size ?

**Comment by jeaunrg** [comment]
youre right, I think I will change the browse button text to the classical '...' and increase the default size. 
But in case the path is really too long, I should add a tooltip which show the whole path, dont you think?

**Comment by Hboni** [comment]
I agree with the new button label.
I think that in some cases, when the path is really really long, using a tooltip can be insufficient. I think that to be able to move in the path using arrows. Or only filename instead of all the path?
It can be an improvement for the futur.

**Comment by jeaunrg** [comment]
Can we close this issue?

**Comment by Hboni** [comment]
Yes, it seems ok, good job!
