### ISSUE TITLE
Threshold parameter selection hard for high values

### ISSUE THREAD

**Issue by Hboni** [Hboni/francis#11]
The threshold node allows to select a threshold value, but only using arrows on the right of the field, which is not convenient if we want to select a threshold like 150. 
Is it possible to have the possibility to fill this field by typing a value in addition to the arrow selection?

**Comment by Hboni** [comment]
I just realized that this way to select values is the same for erosion and dilation processes, I think that all three nodes must have the same selection mode ;)

**Comment by jeaunrg** [comment]
It was the case initially but there is a bug I'm trying to fix...

**Comment by jeaunrg** [comment]
It was a sneaky bug, the proxy of the widget where not focusable in the Node class, then all keyboard inputs are disabled..
Bug fixed!
