### ISSUE TITLE
Error when try to load without image path

### ISSUE THREAD

**Issue by Hboni** [Hboni/francis#21]
When I launch Francis, open a launch nod and click on `apply` without entering a path, the application crash with this error :

    Traceback (most recent call last):
      File "[...]/francis/src/controller/connection.py", line 40, in <lambda>
        w.clicked.connect(lambda: eval(function)(widget))
      File "[...]/francis/src/controller/modules_fn.py", line 58, in loadImage
        im = nib.load(widget.path.text()).get_data()
      File "[...]/francis/venv/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
        raise FileNotFoundError(f"No such file or no access: '{filename}'")
    FileNotFoundError: No such file or no access: ''

I think that this case must just do nothing. I will try to add tests for that ;)

**Comment by Hboni** [comment]
It seems really better. Just to mention, you must not move issues from "To do"/"In progress" to "Done" manually for 2 reasons :
- I think that the issue's author has to validate changes and close the issue before considering finnished.
- Closing an issue will automatically move it to the "Done" part in projects 😉

**Comment by jeaunrg** [comment]
Ok youre right 👍
