### ISSUE TITLE
Improve readability of subtraction and division node 

### ISSUE THREAD

**Issue by Hboni** [Hboni/francis#23]
For subtraction and division node, you have to specify the reference image, but we just have the widget to select the image, but at least a label could help to understand what do you mean with this selection. You can add information in a tooltips if you want to add some description ;)

**Comment by Hboni** [comment]
Nice tooltip! I like it.
But now I do not know if it is normal, but I also have reference for multiply and add, but without a tooltip. Maybe it can be better to complete it for them also?

**Comment by jeaunrg** [comment]
@Hboni can we close this issue? With last updates I think this issue is solved

**Comment by Hboni** [comment]
Oh yeah, thanks for notifying it!
