### ISSUE TITLE
Node widget with left space below

### ISSUE THREAD

**Issue by Hboni** [Hboni/francis#25]
When I have a node that I want to hide parameters, it works fine, but I always have left space below the node. Maybe it would be better to automatically resize node size according to changes in it?
In the same time, using the resizing anchor, I have the possibility to draw this same left space below by dragging down the anchor. What do you think about fixing vertical size, as horizontal size?

(Include in #24)

**Comment by Hboni** [comment]
![francis_node_too_long](https://user-images.githubusercontent.com/27290853/113482246-0126dd80-949e-11eb-9951-7a642e8939e5.png)
(I forgot to update my screenshot as example)

**Comment by jeaunrg** [comment]
Good idea but it is harder than it sounds, I've already tried and it will require many modifications and time, working on it..

**Comment by jeaunrg** [comment]
I found a way!

**Comment by Hboni** [comment]
Awesome, it is woring now! 🎉 
But ..... I found something else. Now the resizing anchor is not on the top of the right for me since your changes 
![francis_resize_anchor](https://user-images.githubusercontent.com/27290853/113521276-bf2e9200-9598-11eb-92d5-1d99b0add064.png)

**Comment by jeaunrg** [comment]
fixed!

**Comment by Hboni** [comment]
Nice job!
