### ISSUE TITLE
Erosion process parameter does not have run/apply button

### ISSUE THREAD

**Issue by Hboni** [Hboni/francis#4]
When opening _erode image_ process parameter window, it only displays some title and the erosion size parameter.
It would be great to have a button to validate the selection of parameters?

**Comment by jeaunrg** [comment]
Is it really useful to add a button to validate, as its a real time process? We apply erosion at each time the erosion size parameter changed.

**Comment by Hboni** [comment]
I agree, but for now, when we open erosion parameter, it not displays the result until I press "Enter", so I think that the display must appear as we open erosion parameter, or we add at least one button to start the display ?

**Comment by jeaunrg** [comment]
I fixed the issue, now the display appear as we open the erosion module.
so I didnt add the button to start display..
